name: bramblur
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_maps: ^6.2.0
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.5
  custom_navigator: ^0.3.0
  drive: ^0.1.0
  flare_flutter: ^3.0.2
  flutter_lints: ^2.0.1
  flutter_signin_button: ^2.0.0
  flutter_google_places: ^0.3.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_remote_config: ^2.0.16
  firebase_storage: ^10.1.0
  google_maps_flutter: ^2.1.0
  http: ^0.13.4
  simple_animations: ^4.0.1
  pedantic: ^1.11.1
  flutter_polyline_points: ^1.0.0
  firebase_storage_web: ^3.1.0
  flutter_rating_bar: ^4.0.1
  google_maps_flutter_web: ^0.4.0+2
  animations: ^2.0.2
  flutter_map: ^2.2.0
  latlong2: ^0.8.1
  vector_tile_renderer: ^2.6.2
  vector_map_tiles: ^2.3.0
  awesome_dialog: ^2.2.1
  cloud_firestore: ^3.4.6
  provider: ^6.0.3
  google_sign_in: ^5.4.1
  equatable: ^2.0.5
  twitter_login: ^4.2.3
  url_launcher: ^6.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
